### ISSUE TITLE
failing the execution of gephi-maven-plugin 

### ISSUE THREAD

**Issue by AmaniChou** [gephi/gephi-maven-plugin#5]
As mentionned in the read me file for the creation of a new plugin, the first step to do is to clone the gephi-maven-plugin and use the generate goal to create the new plugin. After cloning, when I build it an error related to desriptors appears.

> Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:2.9:descriptor (default-descriptor) on project gephi-maven-plugin: Error extracting plugin descriptor: 'No mojo definitions were found for plugin: org.gephi:gephi-maven-plugin.' -> [Help 1]
> 
> To see the full stack trace of the errors, re-run Maven with the -e switch.
> Re-run Maven using the -X switch to enable full debug logging.
> 
> For more information about the errors and possible solutions, please read the following articles:
> [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

 I also tried the **org.gephi:gephi-maven-plugin:generate** goal under rightClickProject- costum- goals of netbeans IDE but it fails to execute.

> Failed to execute goal org.gephi:gephi-maven-plugin:1.2.3:generate (default-cli) on project gephi-maven-plugin: Can't obtain gephi version number -> [Help 1]

**Comment by AmaniChou** [comment]
When I run the generate goal to create a new plugin, I get an error saying Can't obtain gephi version number

> Failed to execute goal org.gephi:gephi-maven-plugin:1.2.3:generate (default-cli) on project gephi-maven-plugin: Can't obtain gephi version number -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.gephi:gephi-maven-plugin:1.2.3:generate (default-cli) on project gephi-maven-plugin: Can't obtain gephi version number
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Can't obtain gephi version number
	at org.gephi.maven.Generate.execute(Generate.java:52)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more

**Comment by LakshmiAntin** [comment]
were you able to resolve this issue?Can you please help me with this?
Thanks.

**Comment by mbastian** [comment]
This isn't a bug in the plugin — the `generate`/`migrate` goals are meant to be run from inside a `gephi-plugins` repository checkout (where `gephi.version` is defined in the root pom.xml), not from a clone of `gephi-maven-plugin` itself. See the [gephi-plugins README](https://github.com/gephi/gephi-plugins#create-a-plugin) for the correct workflow.

That said, the error message here was unhelpful and likely contributed to the confusion, so I've improved it in 74a5202 to explain what's missing and how to fix it.
